language: ruby
rvm:
  - 1.9.3
services: mongodb
before_install:
  - "sudo apt-get install libicu-dev"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
