production:
  sessions:
    default:
      database: compdent_production
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: compdent_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: compdent_test
      hosts:
        - 127.0.0.1:27017
